### ISSUE TITLE
Incorrect table cell reuse in PHImageManager article

### ISSUE THREAD

**Issue by getaaron** [NSHipster/articles#209]
This code is incorrect:

    imageRequests[indexPath] = manager.requestImageForAsset(asset, targetSize: CGSize(width: 100.0, height: 100.0), contentMode: .AspectFill, options: nil) { (result, _) in
        cell.imageView?.image = result
    }

`cell` is no longer guaranteed to relate to this index path. Instead, the code should get the correct cell for the index path from the table view using `indexPath`, and update its image.

Additionally, the documentation doesn't guarantee that this block will be called on the main thread, so unless I'm missing something, that should be done explicitly.

**Comment by getaaron** [comment]
@MBulli You don't need to increment the tag like that. You can use the approach I outlined at the top of the issue: get the cell using the `indexPath` - then it won't matter whether it's been reused or not.

**Comment by natecook1000** [comment]
Thanks, all! This is updated with @getaaron's fix. @rileytestut is right—though the documentation doesn't mention it, the inline comments for `requestImageForAsset` include:

> `// resultHandler for asynchronous requests, always called on main thread`

And @MBulli, that method works well, too, but I'd already hackily used `cell.tag` to fix issue #209.

**Comment by getaaron** [comment]
:+1:

**Comment by MBulli** [comment]
@natecook1000 That's not too bad. Aarons method works as well and isn't causing undefined behavior. @getaaron  Thank you!
