### ISSUE TITLE
PHImage​Manager, cancel previous request when tableViewCell reuse

### ISSUE THREAD

**Issue by meng-zhang** [NSHipster/articles#223]
In the PHImage​Manager article:
"The one tricky part is using imageRequests to keep track of image requests, in order to cancel any pending requests when a cell is reused."
`
if let request = imageRequests[indexPath] {
        manager.cancelImageRequest(request)
    }
`

I am a little confuse of this.

This logic above will cancel the request in the current indexPath which will be load in the next couple of line,  instead of canceling the previous request before the cell reuse.

My solution:
Assign the current PHImageRequestID as the cell's property, when reuse, cancel this request first.

Please correct me if I miss anything.

Thanks a lot.

**Comment by natecook1000** [comment]
Thanks @meng-zhang! This change is in now.
