### ISSUE TITLE
Article suggestion: NSBatchUpdateRequest and NSAsynchronousFetchRequest

### ISSUE THREAD

**Issue by getaaron** [NSHipster/articles#256]
`NSBatchUpdateRequest` and `NSAsynchronousFetchRequest`, two public Core Data APIs [introduced in iOS 8](https://developer.apple.com/library/ios/releasenotes/General/iOS80APIDiffs/frameworks/CoreData.html), are poorly documented. Neither are [included in the official documentation](https://developer.apple.com/library/ios/documentation/CoreData/Reference/NSPersistentStoreRequest_Class/), the [Core Data abstract](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/CoreData_ObjC/) has blank entries for them, and the header files are light on the details.

Big Nerd Ranch has posts on them ([`NSBatchUpdateRequest`](http://www.bignerdranch.com/blog/new-in-core-data-and-ios-8-batch-updating/),  [`NSAsynchronousFetchRequest`](http://www.bignerdranch.com/blog/new-in-core-data-and-iOS-8-asynchronous-fetching/)) but there's still room to expand on their usage.

These would make for a great NSHipster article (hipsters love the obscure). I'd also be happy to pair/collaborate on it if you're interested.

**Comment by natecook1000** [comment]
That's a solid idea, @getaaron, thanks! Added to the list. :smile:

**Comment by bill350** [comment]
Robert Edwards already wrote two good articles :+1: 

https://www.bignerdranch.com/blog/new-in-core-data-and-iOS-8-asynchronous-fetching/

https://www.bignerdranch.com/blog/new-in-core-data-and-ios-8-batch-updating/

Enjoy ;)
