### ISSUE TITLE
Translation Tips and Common Rules

### ISSUE THREAD

**Issue by croath** [NSHipster/articles#277]
FYI: The issue is about summarising the translations tips for new translators and standardising translation.

关于 zh-Hans branch 翻译规范和注意事项的相关讨论，目的是为了总结出一套共同遵循的负责，是翻译专业化、统一化，同时也作为新加入的翻译者的入门手册。

@rickytan @aprilnov @LiLejia

**Comment by rickytan** [comment]
<http://open.leancloud.cn/copywriting-style-guide.html> 一个良好的参考

**Comment by croath** [comment]
@rickytan OK，最好还是把其中觉得可参考的部分贴在这个 issue 里

**Comment by croath** [comment]
我提几个可供讨论的问题先：

1. 英文和中文符号之间是否要有空格
2. 翻译中引号使用 `「」` 还是 `“”`
3. 翻译中的括号使用全角 `（）` 还是半角 `()`
4. `AppDelegate` `block` `Today Extension` 等特制词汇，没有明确的中文翻译时，还要不要翻译
5. 原文中指向站外的链接例如来自 wikipedia 的链接，是否有必要寻找其中文版本
6. 有没有必要上 .tw .hk 站点（或选项），但仅显示 zh-Hans 站点的繁体或正体的机器翻译版本

以及规范相关的：

1. 翻译者如何填写 translator 部分
2. 翻译者翻译文章到达几篇时，可提交 author 信息

等等...

相关的内容，我们讨论出来一条，就向 https://github.com/NSHipster/articles/wiki/Zh-Hans-Translation-Tips-and-Common-Rules. 中更新一条，这样的方式大家接受吧？

**Comment by rickytan** [comment]
1. 英文与中文标点之间还是不要空格了，标点本就就很“空”
2. `“”` 好点吧
3. 标点最好都是与中文等宽的字符，即全角
4. 专有词汇，如果翻译后无法让人第一时间联想到对应代码的哪个概念时，最好保持原有的英文。
5. 我一般会链到中文 Wiki
6. 个人感觉没必要，阅读人数太少，再者，他们英文很强。

_P.S.：_小于等于十的数字个人觉得可以用中文数字

**Comment by aprilnov** [comment]
基本就是按照@rickytan 的来的...另外我如果用到罗马数字的话，都前后空格了...我觉得阿拉伯数字会更醒目一点，中文数字比较不 “跳出”...

**Comment by mattt** [comment]
@croath @rickytan @aprilnov Hey everyone! I've separated out the Chinese language articles into a separate repository here: https://github.com/nshipster/articles-zh-Hans

Please use this repository for all future changes and discussions. Thanks!
