### ISSUE TITLE
Broken relative link in .playground version of XCPlayground article

### ISSUE THREAD

**Issue by wka** [NSHipster/articles#294]
The link to "Swift's _other_ documentation syntax" is a relative link.  This works fine on the website but fails with the error "swift-documentation can't be found" when clicked in the playground.

![screen shot 2015-05-23 at 11 14 19 am](https://cloud.githubusercontent.com/assets/46676/7784693/ebc212e8-013c-11e5-835a-5b76f169b267.png)

Is the `XCPlayground.playground` file is available on Github?  I could not find it otherwise I would have created a PR with a fix.

**Comment by natecook1000** [comment]
Thanks again, @wka! The playground file isn't part of a GitHub repo, as it isn't part of the site in the same way the assets are. I've updated the downloadable one with that change.
