### ISSUE TITLE
waitForExpectationsWithTimeout always calls its block

### ISSUE THREAD

**Issue by multinormal** [NSHipster/articles#306]
Hi

The above post at http://nshipster.com/xctestcase/ says:

> … at the bottom of the method, add the `waitForExpectationsWithTimeout` method, specifying a timeout, and handler to execute if the conditions of a test are not satisfied within that timeframe…

This is incorrect. The docs for `waitForExpectationsWithTimeout` say (emphasis mine):

> … the handler will be invoked **both** on timeout or fulfillment of all expectations.

I.e., code that assumes the execution of the block implies timeout (and hence test failure) will be incorrect. The `waitForExpectationsWithTimeout` function always calls its block. (That the block it takes as an argument takes an error argument doesn't help make this clear, but …)

Thanks for the great work on NSHipster.

**Comment by natecook1000** [comment]
Thanks for pointing this out, @multinormal! :tada:

**Comment by multinormal** [comment]
No worries.
