### ISSUE TITLE
NSCoding / NSKeyed​Archiver article

### ISSUE THREAD

**Issue by almazini** [NSHipster/articles#333]
Hi, it seems that there is an issue in code where you create class. 
I tried to copy it into xcode and debugger shows a lot of errors. 

![screen shot 2015-09-15 at 19 11 39](https://cloud.githubusercontent.com/assets/4295443/9882513/ad7c0d1c-5bdd-11e5-8bed-bce22719da01.png)

**Comment by natecook1000** [comment]
Thanks for bringing this up, @almazini! Please check out [the revised post](http://nshipster.com/nscoding/).

**Comment by almazini** [comment]
Still not working for me, am I importing incorrect library?

![screen shot 2015-09-16 at 07 37 16](https://cloud.githubusercontent.com/assets/4295443/9896519/ee55ddaa-5c45-11e5-81e2-229f9f1c8215.png)

**Comment by natecook1000** [comment]
It looks like you might be using Xcode 6—the code in that article has been updated for Swift 2, so it requires Xcode 7. The `guard` statement is new in Swift 2 and `initWithCoder:` has changed to a failable initializer in Xcode 7.

You should be able to see the Swift 1.2 code [in this version of the post](https://github.com/NSHipster/articles/blob/241345187a94dde18bca5165e7e56ee1268b9eee/2013-05-13-nscoding.md), although you'll still need the memberwise initializer `init()` that is in the latest version.
