### ISSUE TITLE
Elegant defer

### ISSUE THREAD

**Issue by zolomatok** [NSHipster/articles#340]
Not really an issue, just trying to pick a fight:
I think the second usage of `defer` in the [guard & defer](http://nshipster.com/guard-and-defer/) article is elegant, nay, ingenious and actually *more readable* rather than harmful.

;)

**Comment by natecook1000** [comment]
We can agree to disagree. :smile: I wrote a hopefully incontestably horrible example that was too long to include in the post: https://gist.github.com/natecook1000/e6ae2ddfb50ad2147844
