### ISSUE TITLE
Network conditionner access

### ISSUE THREAD

**Issue by ImaCrea** [NSHipster/articles#343]
Hello Mattt,
just to let you know there's been some changes on xcode since your article on network conditionner.

Couldn't find a menu to activate developper settings in iPhone but after plugging it I realized the menu got added to my phone. Don't know if it's because I had already some profiles inside.

See here, I'm not the only one with this issue : http://apple.stackexchange.com/questions/135382/developer-option-is-not-available-under-settings-menu-why?lq=1

Maybe a quick update on that topic could be cool :)

Awesome blog, thanks for sharing buddy.
Max

**Comment by mattt** [comment]
Hi @ImaCrea. Thanks for reporting this issue. I updated the [Network Link Conditioner](https://nshipster.com/network-link-conditioner/) article on July 18, including information about the Developer menu in Settings on iOS. Please let me know if you think there any more changes should be made.
