### ISSUE TITLE
Article on PHImageManager could be more robust.

### ISSUE THREAD

**Issue by JoeyCarson** [NSHipster/articles#347]
First off, thanks for making NSHipster such a great read.

I'm working with image processing in iOS primarily related to CBIR of the photo album using PhotoKit and I've found that Apple's documentation and even WWDC videos don't discuss much of the nuances of the framework. As per usual, Apple only elaborates on the specific use case of fetching photos for display and editing sessions. I've discovered that when actually wanting access to image data itself, the constraints are much tighter and documentation everywhere seems to gloss over this use case. Getting around the nuances of this framework has been frustrating. That's why I think it would be an excellent addition to your article on PhotoKit. Apologies for the verbosity, but theres a lot that can be said about this.

To begin with there are a few API's that allow fetching of images associated with PHAsset objects.

PHImageManager requestImageForAsset will return a UIImage ready for adding to a UIImageView, but the info map will also return other data like the URL of the image in storage. If you try to create a CIImage with this URL, it will fail because the API will not set appropriate permissions for you to access it. The iPhone console will show a permission denied error, though I didn't see this in my own debug console. For image processing purposes, you can copy the underlying data from the UIImage into a CIImage, though you will lose precious metadata like orientation that is necessary for face detection.

So I thought ok I need an API that allows me to access metadata and the image object itself. So I tried PHAsset requestContentEditingInput, which appropriately sets permissions to allow he caller go read the image file at the given URL. This method has two nuances. First, it's callback cannot be controlled to be synchronous, so when indexing images to pass into a database, you must use an asynchronous callback, which is a pain when you're already running a background queue for indexing the photo album. Second, the callback block you specify isn't friendly to being queued into another queue. When that callback block is invoked, as I understand it, it seems to be an IPC message from assetsd under the covers. I was trying to keep my indexing procedure in the background queue and often times the callback was coming in main. If you're running a lot of these, your main thread will be stuck. If you queue the callback block to a background queue, eventually the process crashes with a console error message saying that assetsd connection had died or was interrupted. If you allowed the callback block to run on main or whatever queue the API forced it into, everything will be fine, but if you're doing it heavily, you're blocked.

Finally, I came back to PHImageManager and discovered requestImageDataForAsset. This method was simply bare bones documented and hasn't been elaborated on by anyone. The doc says that it will return to you some image data. From the scope of image processing that could mean so many things. The data could be compressed JPEG or PNG, it could be rendered pixel data in any number of pixel formats, or it could be a serialized object for all I know. It turns out that it can be used with CIImage imageWithData, meaning that it's most likely compressed JPEG or something. But still what a nightmare. This method can be controlled to be synchronous which is perfect for a background NSOperationQueue.

Thanks for your time. If some of this info sounds like something you want to integrate into your article, I'm sure someone will benefit.

**Comment by JoeyCarson** [comment]
I fidn't mean to not leave a description but I don't see how to edit now.  First off, I really enjoy NSHipster, thanks for writing a great blog.  

I'm working with image processing in iOS primarily related to CBIR of the photo album using PhotoKit and I've found that Apple's documentation and even WWDC videos don't discuss much of the nuances of the framework.  As per usual, Apple only elaborates on the specific use case of fetching photos for display and editing sessions.  I've discovered that when actually wanting access to image data itself, the constraints are much tighter and documentation everywhere seems to gloss over this use case.  Getting around the nuances of this framework has been frustrating.  That's why I think it would be an excellent addition to your article on PhotoKit.  Apologies for the verbosity, but theres a lot that can be said about this.

To begin with there are a few API's that allow fetching of images associated with PHAsset objects.  

PHImageManager requestImageForAsset will return a UIImage ready for adding to a UIImageView, but the info map will also return other data like the URL of the image in storage.  If you try to create a CIImage with this URL, it will fail because the API will not set appropriate permissions for you to access it.  The iPhone console will show a permission denied error, though I didn't see this in my own debug console.  For image processing purposes, you can copy the underlying data from the UIImage into a CIImage, though you will lose precious metadata like orientation that is necessary for face detection.

So I thought ok I need an API that allows me to access metadata and the image object itself.  So I tried PHAsset requestContentEditingInput, which appropriately sets permissions to allow he caller go read the image file at the given URL. This method has two nuances.  First, it's callback cannot be controlled to be synchronous, so when indexing images to pass into a database, you must use an asynchronous callback, which is a pain when you're already running a background queue for indexing the photo album. Second, the callback block you specify isn't friendly to being queued into another queue.  When that callback block is invoked, as I understand it, it seems to be an IPC message from assetsd under the covers.  I was trying to keep my indexing procedure in the background queue and often times the callback was coming in main.  If you're running a lot of these, your main thread will be stuck.  If you queue the callback block to a background queue, eventually the process crashes with a console error message saying that assetsd connection had died or was interrupted.  If you allowed the callback block to run on main or whatever queue the API forced it into, everything will be fine, but if you're doing it heavily, you're blocked.

Finally, I came back to PHImageManager and discovered requestImageDataForAsset.  This method was simply bare bones documented and hasn't been elaborated on by anyone.  The doc says that it will return to you some image data.  From the scope of image processing that could mean so many things.  The data could be compressed JPEG or PNG, it could be rendered pixel data in any number of pixel formats, or it could be a serialized object for all I know.  It turns out that it can be used with CIImage imageWithData, meaning that it's most likely compressed JPEG or something.  But still what a nightmare.  This method can be controlled to be synchronous which is perfect for a background NSOperationQueue.

Thanks for your time.  If some of this info sounds like something you want to integrate into your article, I'm sure someone will benefit.

**Comment by mattt** [comment]
Thanks for sharing your feedback, @JoeyCarson. I'm sorry for not responding sooner; your comments came at a time when my employment contract with Apple prevented me from contributing to NSHipster.

As I just mentioned in #633, most of this article was speculation on my part, based on some sketchy intel from the official docs. I didn't have anything notable to add to the discussion beyond spreading awareness that the framework existed. And now, nearly 5 years on, nothing's really changed — I still haven't really used it (though the docs do appear to have filled out quite a bit more).

Given the current state of the article, I decided to retire it for the time being to limit the potential harm by its outdated, incomplete coverage.

If, however, you have any interest in contributing to the site with a new article to replace it, I'd be very interested to work with you to make that happen — you clearly have a great deal of insight that you could share with others about how to work with the PhotoKit framework. Let me know if you'd be interested!
