### ISSUE TITLE
XCTest page

### ISSUE THREAD

**Issue by g3dken** [NSHipster/articles#355]
in this cool article
http://nshipster.com/xctestcase/

this link is broken:
XCTest comes with a **number of built-in assertions**, but

**Comment by natecook1000** [comment]
Thanks for the note, @g3dken! I literally can't find anything in the Apple documentation that that could feasibly point to, so I'm just going to remove the link. Let me know if you have any suggestions, or if you have better luck finding the actual XCTest framework documentation!
