### ISSUE TITLE
Swift Documentation - Special character escape issue

### ISSUE THREAD

**Issue by nicolas-miari** [NSHipster/articles#358]
Right after where it says: "Fenced code blocks are also recognized, with three backticks...", there seems to be an error in escaping special characters so the metioned backticks or tilde are not rendered as supposed:

<img width="952" alt="backticks 2x" src="https://cloud.githubusercontent.com/assets/1000912/11466567/2a9a4448-9785-11e5-812a-c72d603216fd.png">

_(Everything inside the outermost `(` and `)` is rendered as code, the three back ticks are rednered as a back slash, and the tile as a tilde + back tick. )_

*Screen capture shows page as seen in Safari Version 9.0.1 (11601.2.7.2), Mac OS X 10.11(15B42).

**Comment by natecook1000** [comment]
Thanks for this, @nicolas-miari! :+1:

**Comment by nicolas-miari** [comment]
No problem. Did you already fix it, or is it closed because it is "aknowledged"? 

 I just went to the page and it looks like it isn't fixed yet. I even tried `Develop -> Empty Caches` in Safari, then reload. Perhaps it takes time to propagate to mirror servers? I'm in Japan.

**Comment by nicolas-miari** [comment]
OK, now it is fixed. Guess it took time to propagate to my closest mirror server.

**Comment by natecook1000** [comment]
I committed locally and then had to go catch a plane, so it didn't go live for a day or two. Nothing on your end!
