### ISSUE TITLE
Get the Unique Device Identifier Programmatically

### ISSUE THREAD

**Issue by Saraavana** [NSHipster/articles#366]
If this "http://nshipster.com/uuid-udid-unique-identifier/" article, you have specified identifying the "ApplicationUniqueIdentifier" and UUID. These identifier change when the user uninstalls the app. I want to fetch the UDID programmatically(which we can get by connecting the device with iTunes manually). Is there is any way in getting the UDID programmatically?. Any similar to that will be so helpful. Thanks in Advance.

**Comment by natecook1000** [comment]
Apple has gradually removed the different methods of getting hardware-specific identifiers and rejects apps that find workarounds. Stick with the suggestions in the article!
