### ISSUE TITLE
"Avoiding -DDEBUG" snippet does not cover conditional compilation

### ISSUE THREAD

**Issue by DimaVartanian** [NSHipster/articles#367]
Related article: http://nshipster.com/new-years-2016/

Looking through this post and there's a lot of good stuff but this particular piece kind of misses a pretty important reason to use the compiler flags which is actually forcing conditional compilation. Often times you will want to use private or otherwise not-production worthy code/APIs and you would use a compiler flag to avoid compiling those into your production build. Converting these to run time constants and using them in regular conditional statements wouldn't work.

**Comment by mattt** [comment]
Hi @DimaVartanian. I can't speak for @vlat456, but I think [this SO thread](https://stackoverflow.com/questions/24111854/in-absence-of-preprocessor-macros-is-there-a-way-to-define-practical-scheme-spe#comment50839045_29808050) offers a good encapsulation and response to your comment. You're correct about the reasons why someone may want to use `-DDEBUG`, but that's orthogonal to the motivations for this tip.
