### ISSUE TITLE
Fix PHImageManager caching explanation

### ISSUE THREAD

**Issue by ctews** [NSHipster/articles#376]
I read the article regarding [PHImageManager](http://nshipster.com/phimagemanager/), which was a good fast roundup.

In the section **Batch Pre-Caching Asset Images** you suggest the following code:

`cachingImageManager.startCachingImagesForAssets(assets,
    targetSize: PHImageManagerMaximumSize,
    contentMode: .AspectFit,
    options: nil
)`

but I guess a very important part here is to quote the documentation part from :

> Photos caches images with the exact target size, content mode, and options you specify in this method. If you later request an image with, for example, a different target size than you passed when calling this method, Photos cannot make use of the cache and so it must fetch or generate a new image.

So it is very important to state that if you use `PHImageManagerMaximumSize` and you request any different size later on the caching is basically useless. Maybe also add that `PHImageManagerMaximumSize` is defined by  as `Use this size to request the original image data or the largest rendered image available.`

**Comment by mattt** [comment]
Thanks for your feedback, @ctews. Apologies for taking so long to respond.

As I recently mentioned in #347 and #633, this article doesn't meet the site's standards of quality, so I've decided to retire it until such time that it does.
