### ISSUE TITLE
 UISplit​View​Controller no longer compiles using Xcode 7.3

### ISSUE THREAD

**Issue by steegg** [NSHipster/articles#401]
UISplit​View​Controller
Written by Natasha Murashev — November 3rd, 2014

Great article, but unfortunately it no longer compiles using Xcode 7.3. Swift has moved on. Initially there are about 15 errors and warnings. Most can be fixed by selecting the automatic options. That still leaves two errors which are a show stopper for someone coming from Objective-C and not yet versed in Swift.

SelectColorTableViewController.swift:63:16: Initializer for conditional binding must have Optional type, not 'NSIndexPath'

SelectColorTableViewController.swift:78:85: Downcast from 'UITableViewCell?' to 'UITableViewCell' only unwraps optionals; did you mean to use '!'?

**Comment by steegg** [comment]
Ok, after scanning StackOverflow these two changes fixed the problem. Hope this helps someone. Steve

Error 1:

if let selectedRowIndexPath = tableView.indexPathForSelectedRow() {
    let color = colors[selectedRowIndexPath.row]
    colorViewController.color = color
}

let color = colors[tableView.indexPathForSelectedRow!.row]
colorViewController.color = color

Error 2:
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCellWithIdentifier(colorCellIdentifier) as! UITableViewCell
    let color = colors[indexPath.row]
    cell.textLabel?.text = color.displayName
    return cell
}

override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCellWithIdentifier(colorCellIdentifier, forIndexPath: indexPath)
    let color = colors[indexPath.row]
    cell.textLabel?.text = color.displayName
    return cell
}

**Comment by natecook1000** [comment]
Hi @steegg — the full source for that project is in a different repo. If you're up for it, it would be great if you could create a pull request with the changes over there: https://github.com/NatashaTheRobot/UISplitViewControllerDemo
