### ISSUE TITLE
Is ||= a Swift operator?

### ISSUE THREAD

**Issue by kengruven** [NSHipster/articles#419]
Hi, Mattt!

In your [article on Swift operators](http://nshipster.com/swift-operators/), it says that `||=` is "Logical OR and assign".

That would be a useful operator to have, but in Xcode 7.3.1 (whatever version of Swift that is -- 2.2?), I can't get it to work.  This code:

    var a = false
    a ||= true

flags the second line as "Use of unresolved operator '||='".

Apple's documentation is even less clear.  They call them [compound assignment operators](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/BasicOperators.html), and give the example of `+=`, but then says "A complete list of compound assignment operators can be found in [Expressions](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Expressions.html#//apple_ref/doc/uid/TP40014097-CH32-ID383)" and links to a page which doesn't seem to mention them at all.

Do logical compound operators exist in Swift?  Were they perhaps in an earlier release, and removed?  Am I misunderstanding what "Logical OR and assign" means?

(And likewise for other logical operators, I assume.)

cheers,

**Comment by mathewsanders** [comment]
A different Matt here... but I was curious about this too so adding a comment :).

I've looked in the [release notes summary](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html) and don't see anything about `||=` as an operator being removed, so I'm guessing that this is a typo.

But! If you wanted to create this as a custom operator it's pretty straightforward:

```Swift
infix operator ||=  { associativity right precedence 90 }
func ||= (inout left: Bool, right: Bool) {
    left = left || right
}
```

**Comment by natecook1000** [comment]
Hi @kengruven, thanks for the issue! There are no longer logical compound operators in Swift. They must have been present in an early version, but I don't have any record to show when they disappeared—the earliest SwiftDoc header I have is from Swift 1.2b2, and they were already gone by then. I'll remove them from the article.

@mathewsanders Thanks for the implementation! 👍

**Comment by natecook1000** [comment]
Update: go back far enough (around the time of Swift's release) and you can find [the operator declaration](https://github.com/apple/swift/blob/fb93d14aec5d943d10082b394ba00fac7b043ad9/stdlib/core/Policy.swift#L273), but I don't see an implementation anywhere.

**Comment by kengruven** [comment]
Apple's [Swift Standard Library Operators](https://developer.apple.com/reference/swift/1851035-swift_standard_library_operators) table has been updated to include compound operators, and `||=` is not among them, so that's a pretty clear indicator that it's gone for good.
