### ISSUE TITLE
Swift 3 and PermutationGenerator

### ISSUE THREAD

**Issue by WillChilcutt** [NSHipster/articles#435]
Hi, I'm not sure if you're taking issues for Swift 3 changes, but if so feel free to ignore this right now.

It appears in Swift 3 PermutationGenerator was removed. Googling around I came across an [article of NSHipster about NSIndexSet ](http://nshipster.com/nsindexset/) that references it and wanted to give you a heads up that the post might not be valid/relevant anymore =/

Thanks for all of the great material otherwise!

**Comment by natecook1000** [comment]
Thanks! I'm updating articles on a rolling basis as I (or as a contributing reader 😉) see the need. I was sad to see PermutationGenerator disappear, too, though it can be replaced with something like this:

```swift
let elements = ...
let indexSet = ...
let selectedElements = indexSet.lazy.map { elements[$0] }
```

**Comment by WillChilcutt** [comment]
Thanks for the quick response and thanks for the alternative solution! I was going to cast a NSIndexSet in possible and use the enumerate with blocks method instead, but your solution works great too!

Thanks again!
