### ISSUE TITLE
CloudKit and CONTAINS

### ISSUE THREAD

**Issue by ftclausen** [NSHipster/articles#438]
The CONTAINS example [in this article](http://nshipster.com/cloudkit/):

```swift
let predicate = NSPredicate(format: "name CONTAINS 'Apple Store'")
let query = CKQuery(recordType: "Place", predicate: predicate)
```

does not look valid because `CONTAINS` only works with collections and `name` above looks like a string. Or at least the example in the article leads on to believe that CONTAINS will search for substrings within a CloudKit record's text fields.

**Comment by natecook1000** [comment]
Good catch—`CONTAINS` works for strings on normal predicates, but in a `CKQuery` it's only for list membership. I'll update the article when I have a chance—pull requests welcome!
