### ISSUE TITLE
Making Existing Types Inspectable - Impossible

### ISSUE THREAD

**Issue by etayluz** [NSHipster/articles#445]
This great article has one falsehood:
Making Existing Types Inspectable with extensions

This is actually impossible:
http://stackoverflow.com/questions/32468596/ibdesignable-uibutton-extension

Please remove it from the article - it's incorrect.

**Comment by natecook1000** [comment]
That section of the article describes adding `@IBInspectable` properties to existing classes, not making them `@IBDesignable`. As you said, that isn't possible.
