### ISSUE TITLE
Code in article does not compile with XCode 7.3.1

### ISSUE THREAD

**Issue by etayluz** [NSHipster/articles#446]
This code in the article does not compile with XCode 7.3.1:

@IBInspectable var cornerRadius: CGFloat = 0 {
   didSet {
       layer.cornerRadius = cornerRadius
       layer.masksToBounds = cornerRadius > 0
   }
}
@IBInspectable var borderWidth: CGFloat = 0 {
   didSet {
       layer.borderWidth = borderWidth
   }
}
@IBInspectable var borderColor: UIColor? {
   didSet {
       layer.borderColor = borderColor?.CGColor
   }
}

**Comment by natecook1000** [comment]
That's compiling properly for me in the Xcode 8.0 beta against Swift 2.3—can you be more specific about what's going wrong?

**Comment by mattt** [comment]
Closing this issue for due to inactivity. 

@etayluz I'd be happy to reopen if this is still an issue for you.
