### ISSUE TITLE
Incorrect code in CGGeometry article

### ISSUE THREAD

**Issue by LeoNatan** [NSHipster/articles#447]
`func CGRectGet[Min|Mid|Max][X|Y](rect: CGRect) -> CGPoint`

Should be

`func CGRectGet[Min|Mid|Max][X|Y](rect: CGRect) -> CGFloat`

**Comment by mattt** [comment]
Fixed by 539245e7c5bbd74603e96ec06fc9bc5d21eeb1e9. Thanks, @LeoNatan!

**Comment by LeoNatan** [comment]
@mattt You are back? 🤩
Will you be resuming posting articles?

**Comment by LeoNatan** [comment]
https://nshipster.com/return/

❤️❤️
