### ISSUE TITLE
UIKeyCommand (detection of multi-simultaneous key presses and when a key is pressed and released)

### ISSUE THREAD

**Issue by nyteshade** [NSHipster/articles#448]
HELP! I have tried with NSTimers and other approaches, but I can't seem to find a good way to detect multi-key presses using UIKeyCommand (or even hacking around it). The closest I have come is to try and swizzle private methods that expose more information, i.e. lower level information, about the key presses.

UIKeyCommand doesn't seem to allow me to tell when a user is pressing, and holding down, more than one key on a hardware keyboard attached to an iOS device. Any ideas?

You can kind of fake key pressed/key released by setting a key released flag when keyCommands is invoked. But while at least one key press continues to fire events, both or more than two definitely do not. The exception of course being meta keys which is not what I want.

A simple example is, and yes this if for a game, holding down both the up and right keyboard to travel diagonally up and right. I can get very close to this but I haven't been able to actually achieve this since I'm basically guessing when a key is pressed and released.

Know any secrets?

**Comment by mattt** [comment]
Sorry, but I can't offer any guidance for the use case you're describing. `UIKeyCommand` is probably a bad fit for anything other than intercepting specific key combinations. For anything else, you'll want to use lower-level APIs to respond to the events sent on keydown / keyup.
