### ISSUE TITLE
How can I get js callback in WKwebview from js?

### ISSUE THREAD

**Issue by DroidDreamer** [NSHipster/articles#453]
I read your article about WKWebView and really love it .
when in UIwebview, I hook from js through JSContext and act as JSValue.
but when migrating to WKWebview, 
`window.webkit.<name>.postmessage(function())`
cannot work ,  Allowed types are NSNumber, NSString, NSDate, NSArray,
 NSDictionary, and NSNull
Thank you for your attention!

**Comment by orff** [comment]
I found the answer:
https://github.com/NSHipster/articles/issues/499
