### ISSUE TITLE
Strong reference cycle in http://nshipster.com/uialertcontroller/?

### ISSUE THREAD

**Issue by basezen** [NSHipster/articles#454]
It seems in the bottom example, there is a cycle:

`alertController` -> strong ref to `loginAction` (via `addAction`) -> strong ref to anonymous closure (via 3rd parameter in constructor) -> strong reference back to `alertController` (via inclusion in closure function body

I would appreicate being corrected so I understand properly if I'm wrong!

**Comment by natecook1000** [comment]
Fixed, thanks so much!
