### ISSUE TITLE
Missing code in /phimagemanager/

### ISSUE THREAD

**Issue by cdstamper** [NSHipster/articles#463]
# Requesting Asset Images

Code block detailing how to fetch assets, and cancel asset requests, appears to be missing a line of code in the -requestImageForAsset completion block.

Description immediately below code block states:

> The only tricky part is handling cell reuse—(1) before assigning the resulting image to the cell’s image view, we call cellForRowAtIndexPath to be sure we’re working with the right cell

yet the `cellForRowAtIndexPath:` call is missing in the completion block.

Correct usage would look something like:

```
resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
     UITableViewCell *cellCheck = [tableView cellForRowAt:indexPath];
     if (cellCheck) {
          cellCheck.imageView.image = image;
     }
}
```

(note that this brings up several additional issues, including main thread and retain cycle concerns)

**Comment by natecook1000** [comment]
Thanks for seeing that, @cdstamper! Looks like that check disappeared some time back.
