### ISSUE TITLE
NS_ENUM

### ISSUE THREAD

**Issue by gerchicov-bp** [NSHipster/articles#464]
http://nshipster.com/ns_enum-ns_options/

You say "NS_ENUM and NS_OPTIONS macros are the new, preferred way to declare enum types".

Seriously? Try to write code with ```NS_ENUM``` and try to debug it. With ```po <enum_name>``` you will get just numbers.

Of course you could declare it normally and debugger will print you enum member names instead of numbers.

**Comment by mattt** [comment]
Hi @gerchicov-bp. I just tried this in Xcode 10.0 beta (10L176w) and `po` returned the enum name rather than its integer value.
