### ISSUE TITLE
Shouldn't ** operator be right-associative?

### ISSUE THREAD

**Issue by RenniePet** [NSHipster/articles#468]
In your article "Swift Operators" from August 2014, you define the ** operator using Swift's custom operators feature. You define it as "associativity left", but most programming languages implement ** or ^ as right-associative, and that's also the definition for use in mathematics.

https://en.wikipedia.org/wiki/Operator_associativity
http://math.stackexchange.com/questions/1633790/what-is-the-order-when-doing-xyz-and-why

**Comment by mattt** [comment]
You're absolutely correct, @RenniePet. Thanks for pointing this out. The [update to this article on October 3rd](https://nshipster.com/swift-operators/#defining-custom-operators) should get this right.
