### ISSUE TITLE
Swift Operators 3.0 syntax

### ISSUE THREAD

**Issue by AnthonyMDev** [NSHipster/articles#477]
The article on operators is using Swift 2.3 syntax for associativity and precedence configuration still.

This has changed greatly in Swift 3.0, and I'm actually have trouble finding any other source that makes this information clear currently.

**Comment by mattt** [comment]
Hi @AnthonyMDev. I'm happy to report that the Swift Operators article was [updated earlier this month](https://nshipster.com/swift-operators/) for Swift 4.2. Please let me know if you have any suggestions on how to improve or expand upon it further. Thanks!
