### ISSUE TITLE
@IBInspectable default values are not being applied to instances

### ISSUE THREAD

**Issue by rauls4** [NSHipster/articles#480]
When I declare a @IBInspectable with a default value, for example:

@IBInspectable var score:Int = 45

And I assign the class to one of my instances, the Score attribute appears on the attribute inspector pane, but it defaults to -- (nil) instead of 45.

I tried this with multiple examples and none manages to set up the runtime attributes.

If I set a value manually it works as expected but I can't get instances to set to a default value.

Did Apple change something?

**Comment by natecook1000** [comment]
I haven't run into that issue before, sorry!
