### ISSUE TITLE
Link to swift doc for class example is dead

### ISSUE THREAD

**Issue by TheSkwiggs** [NSHipster/articles#484]
I was reading the article http://nshipster.com/swift-documentation/ and when I tried going to the link to see how the full class' documentation looks like I got to a 404.

Here's the reference commit: 48382ee

**Comment by mattt** [comment]
Hi @TheSkwiggs. I fixed this with my update last Wednesday. You should now be able to see that here: https://nshipster.com/swift-documentation-example/classes/bicycle
