### ISSUE TITLE
UIDevice -unique​Identifier

### ISSUE THREAD

**Issue by emranovin** [NSHipster/articles#487]
As I understand, The ID which I retrieve will change if a user removes my app and then install it again. If so what is the best approach to fetch Unique ID which is permanent in All times? I don't like to have different ID from a single device(just because of reinstall). If I was wrong what parameter returns a real Unique ID? which is consistent during all situations.

**Comment by LeoNatan** [comment]
Nothing like that exists. Apple does not want you to track users like that.

**Comment by mattt** [comment]
The functionality you're describing is provided in the [DeviceCheck framework](https://developer.apple.com/documentation/devicecheck), added in iOS 11.
