### ISSUE TITLE
Misunderstanding of G

### ISSUE THREAD

**Issue by andertsk** [NSHipster/articles#488]
What you mean when you say: "where G is one unit of gravity"?
What is the G? Taken from [http://nshipster.com/cmdevicemotion/](url)

Thanks in advance!

**Comment by danielcompton** [comment]
Probably this: https://en.wikipedia.org/wiki/G-force#Unit_and_measurement.

**Comment by mattt** [comment]
Hi @andertsk. @danielcompton is correct, the G in this article refers to the G-force unit.
