### ISSUE TITLE
Hopefully NSHipster will continue updating weekly 

### ISSUE THREAD

**Issue by iAronTalk** [NSHipster/articles#491]
Reading articles on NSHipster is sort of a routine for me, but lately, it seems that NSHipster stopped updating for a really long time, what happened.

**Comment by maoqian0903** [comment]
Does anyone know why stop updating?

**Comment by rickytan** [comment]
Maybe he's just to busy to update this blog weekly 😂

**Comment by rafiki270** [comment]
Matt started working for Apple thus is not allowed to publish anymore I believe

**Comment by mattt** [comment]
Hi @iAronTalk. In case you haven't heard, NSHipster is back to a weekly publishing schedule. For more information, see: https://nshipster.com/return/. Thanks!
