### ISSUE TITLE
Multi-peer connectivity

### ISSUE THREAD

**Issue by BhupendraShekhawat** [NSHipster/articles#497]
How to know when peer device leaves.
and when peer device leaves or disconnect when leaves.

**Comment by daisoreanu** [comment]
You should use the `MCSessionDelegate` :
`- (void)session:(MCSession *)session peer:(MCPeerID *)peerID didChangeState:(MCSessionState)state;`

**Comment by mattt** [comment]
Thanks, @daisoreanu.
