### ISSUE TITLE
Webkit Article

### ISSUE THREAD

**Issue by orff** [NSHipster/articles#499]
you should probably mention that userContentController has to be added to the webView:

let webConfiguration = WKWebViewConfiguration()
     
        let userContentController = WKUserContentController()
        let handler = NotificationScriptMessageHandler()
        userContentController.add(handler, name: "notification")
        webConfiguration.userContentController = userContentController;

 webView = WKWebView(frame: self.view.frame, configuration: webConfiguration)

before you do this, the webkit.message will fail in on the webKit side

**Comment by mattt** [comment]
Apologies for the belated response, @orff. This should now be fixed in [the latest update to the article](https://nshipster.com/wkwebview/)
