### ISSUE TITLE
Swift Documentation for closures as parameters to a method

### ISSUE THREAD

**Issue by david6p2** [NSHipster/articles#505]
Will be nice to know how to document a closure, and the closure parameters, that is passed as parameter to a method. I keep getting a no description square in bottom of the documentation dialog.

<img width="497" alt="screen shot 2018-02-07 at 4 19 17 pm" src="https://user-images.githubusercontent.com/1909725/35942187-d419ced0-0c22-11e8-9504-e622c4552c46.png">

**Comment by mattt** [comment]
Based on what I can tell from the current state of Apple's official developer documentation, this is still an open question. In the meantime, I'd recommend that you describe the closure arguments in prose. As an alternative, you could create and document a typealias for closure types found in multiple methods; however, I'm not personally a fan of the amount of indirection that this approach creates.
