### ISSUE TITLE
printToPrinter() how to implement on swift 4

### ISSUE THREAD

**Issue by NupendraVerma** [NSHipster/articles#508]
Now you can tell your UIPrintInteractionController to print directly by calling printToPrinter(:completionHandler:) with the saved printer instead of using one of the present... methods.

**Comment by mattt** [comment]
That article has not yet been updated for the latest version of Swift. But to answer your question, that API has been renamed to [`print(to:completionHandler:)`](https://developer.apple.com/documentation/uikit/uiprintinteractioncontroller/1618174-print)
