### ISSUE TITLE
Swift GYB

### ISSUE THREAD

**Issue by rickytan** [NSHipster/articles#516]
for code:
```
% for type in codable_types:
  mutating func encode(_ value: ${type}, forKey key: Key) throws
% end
```
It actually generates:
```swift
mutating func encode(_ value: Bool, forKey key: Key) throws
```
the **forKey** parameter is missing <https://nshipster.com/swift-gyb/>

**Comment by mattt** [comment]
@rickytan Good catch! I'd meant to use the variant without the `forKey` parameter for `SingleValueEncodingContainer`.

This is now fixed with 88e504b. Thanks!
