### ISSUE TITLE
Unreadable code boxes in GYB article

### ISSUE THREAD

**Issue by richardgroves** [NSHipster/articles#521]
Not sure if it a browser issue (but tried in Chrome 69 and Safari 11.1.2) but the code boxes in the Swift GYB article at https://nshipster.com/swift-gyb/ are unreadable on my screen - one of the font colours is very very close to the background.

Screen snippet:

<img width="1028" alt="screen shot 2018-08-14 at 12 40 00" src="https://user-images.githubusercontent.com/715058/44089645-79f6e1be-9fbf-11e8-9d68-6991f00bcf89.png">

**Comment by mattt** [comment]
Thanks for pointing this out, @richardgroves. I just pushed a fix for this with 7fbab5f5b6b6af2da0a867457fac97ac3581840a.
