### ISSUE TITLE
code not readable: text and background have same color

### ISSUE THREAD

**Issue by slk333** [NSHipster/articles#523]
take this article for example

https://nshipster.com/swift-gyb/

$ wget https://github.com/apple/swift/raw/master/utils/gyb
$ wget https://github.com/apple/swift/raw/master/utils/gyb.py
$ chmod +x gyb

we cannot read the first two lines because they have the same color (almost) of the code div background

**Comment by mattt** [comment]
Thanks for pointing this out, @slk333. Fixed by https://github.com/NSHipster/nshipster.com/commit/cb4e841.
