### ISSUE TITLE
Broken formatting at the end of NSDataDetector article

### ISSUE THREAD

**Issue by yuriypavlyshak** [NSHipster/articles#525]
https://nshipster.com/nsdatadetector/

Text at the end looks like this:
![image](https://user-images.githubusercontent.com/3767576/44580159-37096e80-a799-11e8-98c3-65a3c19128fd.png)

**Comment by mattt** [comment]
Thanks for opening an issue, @yuriypavlyshak. I'm happy to say that not only is the formatting now fixed, but the entire article is now updated and expanded for Swift 4.2: https://nshipster.com/nsdatadetector/. Hope you like it!
