### ISSUE TITLE
UIFieldBehavior has undefined variable `scale`

### ISSUE THREAD

**Issue by bryanjclark** [NSHipster/articles#529]
On line 232 of the UIFieldBehavior post:
https://github.com/NSHipster/articles/blame/master/2018-09-24-uifieldbehavior.md#L232

...there's a variable `scale` mentioned in the source code, but not explained in the surrounding text. Maybe the code needs a comment, or maybe the `scale` isn't needed / meant to be there? In the Objective-C code, the region is divided in half - so perhaps that's what's missing here?

**Comment by mattt** [comment]
Thanks for catching that, @bryanjclark. `scale` is an affine transform to scale size by half. It's now included with 0c3afe0.
