### ISSUE TITLE
How to mock the API in objectivec for unit test

### ISSUE THREAD

**Issue by kkukkadapua** [NSHipster/articles#533]
please can you help me to write the mock data for API Call in ios objective c.

**Comment by Ricardo1980** [comment]
Ah OK.
I don't remember in objc, but I am sure there are several libraries for doing that, although maybe they are old.

**Comment by kkukkadapua** [comment]
can you suggest any libraries for objective c.

**Comment by Ricardo1980** [comment]
I remember many many years ago I used OCMock for that, but I don't remember the details.
Search something
Check also 
http://blog.grio.com/2013/04/faking-network-calls-for-ios-unit-tests.html

**Comment by kkukkadapua** [comment]
thanks bro ... i will look into it..
