### ISSUE TITLE
Article 'Date​Components' – comparing with granularity

### ISSUE THREAD

**Issue by thorstenstark** [NSHipster/articles#535]
Great article!
What I also like about 'Calendar' and 'DateComponents' is that you can compare two dates with a specified granularity i.e if both are the same day or week:
```swift
let calendar = Calendar.current
calendar.compare(date1, to: date2, toGranularity: .day)
```

**Comment by mattt** [comment]
Yeah, that's a great API. Super useful! An earlier draft included discussion of this, but I decided to remove it for the final version to focus on `DateComponents`-specific functionality.
