### ISSUE TITLE
Language Server Protocol question

### ISSUE THREAD

**Issue by LucianoPAlmeida** [NSHipster/articles#544]
Hey @mattt 
The Language Server Protocol article is awesome. Thank you for providing such good content to the community :))
My question is on the section bellow:
<img width="958" alt="screen shot 2018-11-07 at 12 53 25 pm" src="https://user-images.githubusercontent.com/8292651/48142982-a0732680-e28c-11e8-9cb7-c7599dda6b51.png">
Is it correct to say the Clang is a frontend for Swift and C languages? I thought it clang was the frontend just for C languages and the swiftc was the one for Swift. It that right?

**Comment by mattt** [comment]
Hi @LucianoPAlmeida. Clang is indeed a frontend for C languages, and it would not be correct to say that it's a front-end for Swift. What I meant by "The LLVM compiler frontend used by Swift and C languages..." is that Swift uses Clang for interoperability with C and Objective-C.

**Comment by LucianoPAlmeida** [comment]
Hey @mattt :))
Thank's for the response it makes sense now, my comment was just that is implicitly, and people who read it and don't know much about compilers may think that you can compile swift with Clang. 
Maybe if the phase was more explicit like "The LLVM compiler frontend for C languages that is also used by Swift for interoperability with C and Objective-C is called Clang". 
It's just a suggestion that maybe can avoid confusion.
And again thank you for taking the time to answer 😊
