### ISSUE TITLE
How do I understand this sentence?

### ISSUE THREAD

**Issue by Adolf-L** [NSHipster/articles#547]
Hello Mattt

I have a question about this "Time​Interval, Date, and Date​Interval" article!

> Seconds are the fundamental unit of time. They’re also the only unit that has a fixed duration.

How do I understand the word "only"?
Why hours or minutes are not only unit has a fixed duration?

Can you explain it more? thank you !

**Comment by mattt** [comment]
A positive or negative leap second can affect the duration of the last minute and hour of a year (i.e. 59 or 61 second minute / 3599 or 3601 second hour): https://en.wikipedia.org/wiki/Leap_second
