### ISSUE TITLE
Missing something about simctl

### ISSUE THREAD

**Issue by mayoff** [NSHipster/articles#548]
[In the simctl article](https://nshipster.com/simctl/), there's something missing after “However, the”.

<img width="272" alt="screen_shot_2018-11-26_at_2_56_39_pm" src="https://user-images.githubusercontent.com/247531/49041913-31526900-f18c-11e8-818e-d3651d754206.png">

**Comment by mattt** [comment]
Whoops! Thanks for catching that, @mayoff. Fixed by bc58c01.
