### ISSUE TITLE
How to import Contacts in Swift Playgrounds for iPad?

### ISSUE THREAD

**Issue by lochiwei** [NSHipster/articles#552]
You imported Contacts framework in your post:
https://nshipster.com/customplaygrounddisplayconvertible/

But when I tried to do the same thing in my iPad, I got the error:
"No such module"

How to fix this problem? thanks.

**Comment by mattt** [comment]
Thanks for bringing this to my attention, @lochiwei.

Swift Playgrounds (which are distinct from Xcode Playgrounds) restrict which frameworks are available to use from the SDK. I couldn't find the official list from Apple's documentation, but [here's a Gist](https://gist.github.com/filippocld/612090502dcdd1f698f7f83bca3343ca) detailing which frameworks can and can't be used. According to this list, Contacts and ContactsUI are, unfortunately, not available in Swift Playgrounds.

I added a note about this with 027353a.
