### ISSUE TITLE
'contact' is a get-only property?

### ISSUE THREAD

**Issue by lochiwei** [NSHipster/articles#553]
in your post: https://nshipster.com/customplaygrounddisplayconvertible/

the following line:
viewController.contact = self

leads to the following error on my MacBook Air:
Cannot assign to property: 'contact' is a get-only property

any ideas?

**Comment by mattt** [comment]
Annoyingly, ContactsUI exposes slightly different APIs in macOS and iOS. In the case of the `contact` property, it's readwrite on macOS and readonly on iOS: https://developer.apple.com/documentation/contactsui/cncontactviewcontroller/1522596-contact

I fixed this with 8ab5dd204030eb0288809f5571a4b61a66283a66.
