### ISSUE TITLE
Dark Mode CSS: Strikethrough Text is Wrong Color

### ISSUE THREAD

**Issue by hisaac** [NSHipster/articles#557]
I just noticed in the [recent article on Homebrew](https://nshipster.com/homebrew/) that the struck-through text in the "Creating a Makefile" section is dark colored when the site is in dark mode. Here's a screenshot:

![screen shot 2018-12-03 at 7 51 20 am](https://user-images.githubusercontent.com/923876/49377736-90eece00-f6d0-11e8-9a04-cc1538435435.png)

It looks like this is set by the CSS at [line 537](https://github.com/NSHipster/nshipster.com/blob/24d4147c1726e2d92f4206c701c9815c56872261/assets/css/_layout.scss#L537) in `_layout.scss`.

**Comment by mattt** [comment]
Nice catch! Fixed by 0e588a9c715e2f09b0c487bca22f7337a395717e. Thanks, @hisaac!

**Comment by hisaac** [comment]
You're welcome!
