### ISSUE TITLE
Article 2018-07-23-uitextinputpasswordrules has bad advice

### ISSUE THREAD

**Issue by henkalni** [NSHipster/articles#558]
Article states as follows

> In stark contrast, good passwords are the opposite of artisanal. Unless it's the title of a hacker movie from the 90's or the solution to an escape room puzzle, a password should be utterly devoid of meaning.

Which is in direct contrast to the referenced NIST guidelines where is stated that the length of memorized secret should be the primary factor characterizing a password. Point of memorized secret is to be "something you know" rather than something you write down and _have_. Password should be devoid of meaning if it is randomly generated and stored safely i.e. password manager.

**Comment by mattt** [comment]
I don't find those statements to be in direct contrast to the guidelines.

According to the cited [NIST Digital Identity Guidelines](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf), the length of the memorized secret is the primary but not the only factor:

> #### 5.1.1.2 Memorized Secret Verifiers
> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. For example, the list MAY include, but is not limited to:
> * Passwords obtained from previous breach corpuses.
> * Dictionary words.
> * Repetitive or sequential characters (e.g. ‘aaaaaa’, ‘1234abcd’).
> * Context-specific words, such as the name of the service, the username, and derivatives
thereof.

The "title of a hacker movie from the 90's" and "the solution to an escape room puzzle" are both examples of dictionary words, which according to these guidelines make poor secrets. The phrase "a password should be utterly devoid of meaning" is in reference to the general guidance that passwords with _a priori_ meaning are typically dictionary words or the like.
