### ISSUE TITLE
NSFileManager article

### ISSUE THREAD

**Issue by jacopo-nextology** [NSHipster/articles#56]
In the article for the NSFileFormatter, in the examples, you are using the API with the NSString path, but in the documentation Apple states that is always preferable use the NSURL methods because the NSURL can store more efficiently the path informations.
So is preferable ditch the use of the NSSearchPathForDirectoriesInDomains method and switch to the URLsForDirectory:inDomains:. The latest return an NSArray but of NSURL objects that conforms better with the Apple's recommendations.

**Comment by mattt** [comment]
Thanks for sharing your feedback, @jacopo-nextology. I recently updated this article, and made a point to motivate and advocate the use of URL-based APIs. See: https://nshipster.com/filemanager/
