### ISSUE TITLE
GYB is not a reference to GYP, but to SYB

### ISSUE THREAD

**Issue by dabrahams** [NSHipster/articles#561]
https://nshipster.com/swift-gyb/ mentions GYP, which I'd never heard of.  It's actually inspired by https://hackage.haskell.org/package/syb

Cheers

**Comment by mattt** [comment]
Ah, apologies for assuming incorrectly. Thanks for setting the record straight, @dabrahams!

I just updated the article to correct the etymology with 3248851.

**Comment by dabrahams** [comment]
Thanks.  Sorry, I don't mean to nitpick, but it's a reference to the paper that inspired the package, rather than the package itself.  FWIW.

**Comment by dabrahams** [comment]
https://www.microsoft.com/en-us/research/wp-content/uploads/2003/01/hmap.pdf
