### ISSUE TITLE
Never as a bottom type

### ISSUE THREAD

**Issue by vincent-pradeilles** [NSHipster/articles#563]
The article on `Never` states:

> An uninhabited type can be seen as a subtype of any other type — if evaluating an expression never produces a value, it doesn’t matter what the type of that expression is.

A really cool and insightful way to illustrate this fact is with this Swift function:

```swift
func absurd<T>(_ never: Never) -> T {
    switch never {
        
    }
}
```

It might seem weird at first glance, but this function compiles without a hitch (at least, as of Swift 4.2). And it's a perfect illustration, that, if an expression can never be called, it can take whatever type we want.
And it's also rather insightful, because from a logical standpoint, it's the illustration of this principle: [https://en.wikipedia.org/wiki/Principle_of_explosion](https://en.wikipedia.org/wiki/Principle_of_explosion).

**Comment by mattt** [comment]
That's a great example, @vincent-pradeilles. Thanks for sharing that!

The article on Never currently uses the following code example to illustrate what I believe to be the same kind of consequence (right above ["Never as a Bottom Type"](https://nshipster.com/never/#never-as-a-bottom-type)):

```swift
extension Never: Comparable {
  public static func < (lhs: Never, rhs: Never) -> Bool {
    switch (lhs, rhs) {}
  }
}
```

My intention was to use this example and the discussion that followed as a transition to the section about bottom types:

> Because Never is an uninhabited type, there aren’t any possible values of it. So when we switch over lhs and rhs, Swift understands that there aren’t any missing cases. And since all cases —- of which there aren’t any — return Bool, the method compiles without a problem. 

Do you believe the `absurd(_:)` represents a distinct result from the current example? How would you suggest revising the article to clarify or expand these ideas?
