### ISSUE TITLE
Testing whether a file is a package

### ISSUE THREAD

**Issue by tempelmann** [NSHipster/articles#564]
You could also use Launch Services:

1. Skip if it's not a directory.
2. Call LSCopyItemInfoForURL with inWhichInfo = kLSItemInfoIsPackage
3. Check the returned flags for the kLSItemInfoIsPackage mask.
Huh - this gives a deprecation warning, saying: "Use the URL resource property kCFURLIsPackageKey or NSURLIsPackageKey instead."

So, it's all much easier, even, see https://stackoverflow.com/a/27713709/43615

Simply get the NSURL's NSURLIsPackageKey via getResourceValue:forKey:error: - that's clearly shorter than the acticle's proposed method of first creating a UTI for the file's extension. Or am I overlooking something?

**Comment by mattt** [comment]
Thanks for the tip, @tempelmann! That is indeed much simpler.

I've updated the article accordingly with 2638f5f.
