### ISSUE TITLE
Regarding discussion of HTTP content negotiation in 2012-09-03-locale.md

### ISSUE THREAD

**Issue by kasei** [NSHipster/articles#567]
The Locale article includes this:

```
If your app communicates with a web app over HTTP, you might use this property to set the Accept-Language header field to give the server an opportunity to return localized resources
```

Using the sample code, I find an accept header value that looks something like `"en-US,ja-US"`; country code language subtags always seem to be included. I'm not sure if there's a way to get a non-country-coded language tag out of `Locale`, but as written I'm not sure this part of the article is very helpful since it essentially tells servers (e.g. for "en-US") "I only prefer American English". That is, non-country-specific English, or British English, or any other sort of English are *not* counted as acceptable to the client. This probably isn't what the app developer intends.

I'd love to see an update that amended the sample code to get a better `Accept-Language` header value that leads to more sensible content-negotiation, or at least some mention that care should be taken in using the language codes that come straight out of `Locale` since their content negotiation semantics might be surprising.

**Comment by mattt** [comment]
Hi @kasei. Your assessment indeed comports with this note from [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.5):

> Note: User agents ought to provide guidance to users when setting
> a preference, since users are rarely familiar with the details of
> language matching as described above.  For example, users might
> assume that on selecting "en-gb", they will be served any kind of
> English document if British English is not available.  A user
> agent might suggest, in such a case, to add "en" to the list for
> better matching behavior.

I was writing with this specifically in mind when writing this article, based on my understanding of how `preferredLangauges` behaves. For example, here's what I get running it locally (macOS Playground):

```swift
import Foundation

Locale.preferredLanguages.joined(separator: ",") // "en,en-US,ja-US"
```

So I'm surprised to see that you get different results that don't include the unqualified `en` language tag in addition to the `US` regional variant. Though, the documentation doesn't really say anything about how this is expect to behave, so we shouldn't behave on any particular behavior.

With 4fd3805, I added the following note to expand on this:

> [HTTP content negotiation](https://tools.ietf.org/html/rfc7231#section-3.4)
> is a complex topic,
> and apps interacting with localized, remote resources
> should use `Locale.preferredLanguages` as a starting point
> for generating a more precise `Accept-Language` field value.
> For example,
> you might specify an <dfn>associated quality value</dfn>
> like in `en-SG, en;q=0.9`
> to tell the server
> _"I prefer Singaporean English, but will accept other types of English"_.
> 
> For more information,
> see [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.5).

Does this address your concerns? If not, do you have any suggestions for how to further clarify?

**Comment by kasei** [comment]
Oh. That is very interesting that you get a non-region-specific `"en"` value! I wonder what difference in our respective configurations causes that. I think this added text does a fine job addressing my concern. Thanks!
