### ISSUE TITLE
Expressible​By​String​Interpolation use yyyy for date-format example but a single y is better.

### ISSUE THREAD

**Issue by JGiola** [NSHipster/articles#576]
At least for NSDateFormatter instances we can do better than `yyyy` with even less character use. As beautifully posted by Erica Sadun [here](https://ericasadun.com/2018/12/25/iso-8601-yyyy-yyyy-and-why-your-year-may-be-wrong/) is better to use a single `y` because `yyyy` will add 0 padding to the years with less than 4 character, as with the Japanese calendar.

**Comment by mattt** [comment]
@JGiola In the article, my example was “to create a string representation of a date that included its 4-digit year.”  On review, I concede that it’s insufficiently motivated, and agree with your assessment about “y” being a better fit. I've made that change with a894a78, which is now live.
