### ISSUE TITLE
A broken link to IBM's website

### ISSUE THREAD

**Issue by jkmassel** [NSHipster/articles#586]
The link to IBM's Globalization Guidelines is broken at https://nshipster.com/launch-arguments-and-environment-variables/#nsdoublelocalizedstrings.

I wasn't able to immediately find a replacement link for it 😞

**Comment by mattt** [comment]
Thanks for the heads-up, @jkmassel. I'll update that to point to [this page on the CLDR website](http://cldr.unicode.org/index/cldr-spec/plural-rules).
