### ISSUE TITLE
Temporary Directory: destinationURL is not initialized before call to url(for:in:appropriateFor:<here>create:)

### ISSUE THREAD

**Issue by alexbbrown** [NSHipster/articles#600]
https://nshipster.com/temporary-files/

In the following example

destinationURL is not initialized before it's consumed.  What is the intention here?
```
let destinationURL: URL

let temporaryDirectoryURL =
    try FileManager.default.url(for: .itemReplacementDirectory,
                                in: .userDomainMask,
                                appropriateFor: destinationURL,
                                create: true)

let temporaryFilename = ProcessInfo().globallyUniqueString

let temporaryFileURL =
    temporaryDirectoryURL.appendingPathComponent(temporaryFilename)
```

**Comment by mattt** [comment]
The intention was for the `destinationURL` declaration to be a placeholder, to have its value specified by a sample code consumer. We've since added support for Xcode-style `<#placeholder#>` tags. With 87558b1744fbe28189e8edd0bd5317eca75010c9, the article has been updated to use those instead.
