### ISSUE TITLE
UITableViewHeaderFooterView, AutomaticDimension

### ISSUE THREAD

**Issue by armandzwan** [NSHipster/articles#602]
Have you ever tried AutomaticDimension and AutoLayout with UITableViewHeaderFooterView?

Feels like the OS cannot calculate the title label height correctly when the title is very long and spans more than one line. Having all sorts of issues with it.

First time it loads all is sort of OK (sometimes extra top and bottom margins?), but if you rotate your device... Especially when starting your app in landscape and then rotate to portrait.

Give it a try if you have some hours left! ;-)

**Comment by mattt** [comment]
Thanks for the feedback, @armandzwan. I just added a new section covering this in 0e66b98 and d165830. Does this address your problems?

https://nshipster.com/uitableviewheaderfooterview/#self-sizing-header-and-footer-views
