### ISSUE TITLE
Optional, throws, Result, and async/await... and Rx

### ISSUE THREAD

**Issue by hmlongco** [NSHipster/articles#606]
"And, in fact, this is even more of an issue in the async space since flatMap expects its transform to return synchronously. So we can’t use it to compose asynchronous operations. ... In the near term, we just have to lump it"

Or use Rx. In this case, RxSwift in particular.

Because with RxSwift you can, in fact, flatpMap across multiple asynchronous operators and catch errors at the end.

```
_ = savebutton.rx.tap
    .flatMap { someObservableNetworkOperation() }
    .flatMap { anotherObservableNetworkOperation() }
    .subscribe(onNext: { result in
        // handle result, assume operations complete
    }, onError: { e in
        // handle error
    })
```

So yes, we don't have async/await and as such there isn't a simple Swift way to handle async calls... but there is a simple RxSwift way...

Very nice article, btw.

**Comment by jemmons** [comment]
@hmlongco A good point! The only issue I had was, in keeping with the “from first principals” nature of the post, I didn't feel like I could say something like “or use Rx” without explaining Observables and pub/sub and Disposables and all that jazz about *how* Rx deals actually deals with the async problem (and one could substitute “Rx” with “Promises” or “Actors” or “the Continuation Monad” or…).

But I'm very glad you bring it up here.

**Comment by hmlongco** [comment]
Actually, if you want to use "pure" Swift 5.0...........
```
    enum NWError: Error {
        case notFound
        case failed
    }

    // a dummy api request
    func apiTest(_ dummy: String? = nil) -> Result<String?, NWError> {
        guard let url = URL(string: "https://jsonplaceholder.typicode.com/todos/1") else {
            return .failure(.notFound)
        }

        var result: Result<String?, NWError>!

        let semaphore = DispatchSemaphore(value: 0)

        URLSession.shared.dataTask(with: url) { (data, _, _) in
            if let data = data {
                result = .success(String(data: data, encoding: .utf8))
            } else {
                result = .failure(.failed)
            }
            semaphore.signal()
            }.resume()

        _ = semaphore.wait(wallTimeout: .distantFuture)

        return result
    }

    func test() {
        OperationQueue.background.addOperation {
           // make first api call and flatMap second api call
            let result = self.apiTest()
                .flatMap { self.apiTest($0) }

           // handle result
            switch result {
                case let .success(data):
                    print(data)
                case let .failure(error):
                    print(error)
            }
        }
    }
```
The GCD semaphores let us use a async function call as if it were synchronous, and the new flatMap operation on result lets us chain those operations together. 

If the first call errors out then the error is propagated forward as the end result .failure state.

This is, if you don't mind my saying so, pretty slick.

**Comment by hmlongco** [comment]
@jemmons [Swift 5 Result and GCD](https://medium.com/@michaellong/how-to-chain-api-calls-using-swift-5s-new-result-type-and-gcd-56025b51033c)
