### ISSUE TITLE
UIImageView JPEG Decoding

### ISSUE THREAD

**Issue by MohammadFahmaanKhan** [NSHipster/articles#612]
In the NSHipster [article about resizing images](https://nshipster.com/image-resizing/), there was an interesting tidbit about how UIImageView works and why resizing is important for low memory usage:

_**To display it, a UIImageView needs to first decode that JPEG into a bitmap.**_

Where did you guys find this? I went through the UIImageView documentation and couldn't find a reference to this statement anywhere. It would be cool to know, had I known this earlier it would have been beneficial... 

Thanks!

**Comment by mattt** [comment]
To clarify: The process of decoding a JPEG into image bitmap data is the responsibility of `UIImage` by way of the [Image I/O framework](https://developer.apple.com/documentation/imageio). By the time you have a `UIImage` object to display, that work is already done. So it's understandable that this isn't discussed in the documentation for `UIImageView`. 

That said, Apple's current documentation website is still missing a lot of information from the old programming guides, [like this one for Image I/O](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_basics/ikpg_basics.html). If you were interested in learning more about how that works, I'd suggest reading through that and other guides like that.
