### ISSUE TITLE
Why Enum for Configuration/API Definitions

### ISSUE THREAD

**Issue by DrCarleeknikov** [NSHipster/articles#616]
In your **Xcode Build Configuration Files** article you used empty Enums as the base for your Configuration and API objects. Was there any specific reason for this? I've never considered this and was wondering the advantages of this over using a struct.

**Comment by mattt** [comment]
See https://nshipster.com/never/#uninhabited-types

**Comment by DrCarleeknikov** [comment]
Thank you so much! I just want to let let you know how much I have appreciated your work over the years! When I was just beginning to learn iOS development (2008ish) I interacted with you on StackOverflow, CocoaPods, and NSHipster; all without realizing that you were all three people. One day, it dawned on me and I chuckled to myself. So, thank you again!

**Comment by mattt** [comment]
@DrCarleeknikov Thanks so much for your kind words! That means a lot. I'm so happy that you've found my work to be helpful.

And yeah, Swift enumerations are super interesting — they can do way more than their name seems to imply. My favorite use of them in my own projects is for [Money](https://github.com/flight-school/money).
