### ISSUE TITLE
question on https://nshipster.com/xcconfig

### ISSUE THREAD

**Issue by chenxi141017** [NSHipster/articles#619]
> Therefore, by adding references to $(API_BASE_URL) and $(API_KEY), you can access the values for those settings through the infoDictionary property of Foundation’s Bundle API.

I'm confused about how to adding reference?

After Google I found two ways to adding reference.

1. Add a new key-value in Info.plist file
 I set a new key named `API_BASE_URL` and set it's value is `$(API_BASE_URL)`, then I can access the value from the following code

```
NSDictionary *dictionary = [NSBundle mainBundle].infoDictionary;    
NSLog(@"API_BASE_URL = %@", [dictionary objectForKey:@"API_BASE_URL"]);
```

2. Append preprocessor directive in `xcconfig` file

I append preprocessor directive `GCC_PREPROCESSOR_DEFINITIONS = $(inherited) API_KEY='$(API_KEY)' `, then I can access the value from the following code

```
NSLog(@"%s", API_KEY);
```

So my question is: is there any other way to adding reference ?

**Comment by mattt** [comment]
The first method you listed is the approach I'm describing in the article. I don't doubt that there are other ways to get the same result, but my recommendation would be to go with that.

I just added a new screenshot to clarify how to add that key to Info.plist in Xcode.
