### ISSUE TITLE
Question regarding UILocalizedIndexedCollation

### ISSUE THREAD

**Issue by JakeRL** [NSHipster/articles#624]
Just read the https://nshipster.com/uilocalizedindexedcollation/ article and am wondering what concerns I should have in foregoing UILocalizedIndexedCollation and instead opting to build section titles by looking at the first characters of my data set (coming down from an API in this case), comparing those characters as localized strings. Mirroring the snippet in the article, something like...

```swift
class StringTableViewController: UITableViewController {
  private(set) var sectionIndexTitles = [String]()

  var strings: [String] = [] {
    didSet {
      let groupedStrings = Dictionary(grouping: strings, by: { $0.prefix(1).localizedCapitalized })

      sectionIndexTitles = groupedStrings.keys.sorted { lhs, rhs in
        lhs.localizedStandardCompare(rhs) == ComparisonResult.orderedAscending
      }

      self.tableView.reloadData()
    }
  }

  // MARK: UITableViewDelegate

  override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
    return sectionIndexTitles[section]
  }

  override func sectionIndexTitles(for tableView: UITableView) -> [String]? {
    return sectionIndexTitles
  }
}
```

**Comment by mattt** [comment]
Hey @JakeRL. Thanks again for #623!

Overall, I'd say this implementation gets a lot right. The use of `localizedStandardCompare` and  `localizedCapitalized` here is 👌. For most use cases, this would probably work fine.

However, collation is an enormously complicated problem with locale-specific rules and exceptions. See: [UTS #10](https://unicode.org/reports/tr10/). For example, `$0.prefix(1)` may be problematic for digraphs like [CH](https://en.wikipedia.org/wiki/Ch_%28digraph%29), which some locales treat as a _collation grapheme cluster_. Also, this approach may not correctly handle locales with expanded and contracted forms, like "æ" and "ae".

And then there's emoji, which probably should be collated into a single bucket (or maybe per-category, like in the emoji keyboard). By my reading of the code, the current behavior would provide section indexes for each individually.

But assuming you did produce correct section index titles, there's the whole other question of which ones should be displayed for a particular locale. For example, Americans might be surprised to find separate indexes for A and Ä.

Without knowing more about your motivation, I'd generally advise using what's provided by `UILocalizedIndexedCollation`. Without specific insight into how `UILocalizedIndexedCollation` works internally, the notion of "correctness" is taken as an article of faith. But even in cases where its behavior deviates from the Unicode Standard, it's probably not a bad idea to be consistent with the rest of the system.

**Comment by JakeRL** [comment]
Thanks for the detailed reply, @mattt. Also my pleasure to help re: #623.

I owe that use of `localizedStandardCompare` and `localizedCapitalized` all to you and Flight School! Guide with Swift Strings was a great read and continues to be a super helpful resource. Working my way now through the last pages of Numbers and plan on picking up Codable any day now; I can't get enough.

Anywho, we've opted back into leveraging `UILocalizedIndexedCollation` and you've pointed some good, concrete examples of where that will help. At a high level, I knew there was probably trouble lurking somewhere but was struggling to think up the specifics.

Thanks again!
