### ISSUE TITLE
Question on XPC Services - https://nshipster.com/inter-process-communication

### ISSUE THREAD

**Issue by sathwikmatsa** [NSHipster/articles#625]
The bundled XPC Service in my macOS application need to do some post processing work with files dumped by the parent app, which most probably can't be completed within the usage time of the application. So, Is there a way to make the XPC service keep running even after the user quits the main app?

**Comment by mattt** [comment]
@sathwikmatsa One pattern I've seen with several macOS apps is to have a helper application that runs separately from the main app. My understanding is that this helper application does processing in the background and communicates with the main app (when active) via XPC. To see some examples on your own machine, open Activity Monitor and search for processes with names containing "Helper" or "Agent".
