### ISSUE TITLE
Image resize techniques, Technique #1 

### ISSUE THREAD

**Issue by mndgs** [NSHipster/articles#626]
Trying Technique #1 against default sample image from iOS Simulator and it takes ~ 5 or more seconds to resize.  Not sure why (heif codec?), other images perform much better, inline with your numbers 

The image in question:
![image](https://user-images.githubusercontent.com/5536778/59180597-04850280-8b6e-11e9-9c9c-e8e71662926a.jpeg)

Tested on device and Playgrounds, code from Playgrounds:
(copied image to Playground's Resources)

    import UIKit

    func resizedImage1(at url: URL, for size: CGSize) -> UIImage? {
        guard let image = UIImage(contentsOfFile: url.path) else {
            return nil
        }
    
        let renderer = UIGraphicsImageRenderer(size: size)
        return renderer.image { (context) in
            image.draw(in: CGRect(origin: .zero, size: size))
        }
     }
    
    let size = CGSize(width: 32, height: 32)
    let url = Bundle.main.url(forResource: "image", withExtension: "jpeg")!

    print(Date())
    let image = resizedImage1(at: url, for: size)
    print(Date())

**Comment by mattt** [comment]
@mndgs Performance on an iOS Simulator or in a Playground may not be (and often isn't) characteristic of performance on an actual device, which is the focus of the article. I can't personally account for these differences, but would encourage you to use any of the alternative approaches if they're more suitable for your specific use case.
