### ISSUE TITLE
Security Concern About https://nshipster.com/xcconfig/

### ISSUE THREAD

**Issue by tonyli508** [NSHipster/articles#636]
Hi @mattt,

Just finish reading of https://nshipster.com/xcconfig/, great article. 

A question pop up during reading, if you left `API SECRET` in Info.plist, wouldn't that be a security concern? Someone can easily get that, right?

**Comment by mattt** [comment]
That's a great point, @tonyli508, thanks for bringing it up.

The unfortunate truth of the matter is that nothing in your compile app can be kept secret. Anyone with enough know-how and effort can decompile and analyze your app to find hard-coded credentials, or install an intermediary certificate and intercept network traffic. You can take steps to obfuscate this information, but it's best to assume that nothing in your compiled code is safe.

Instead, the server should be responsible for authorizing and authenticating requests for resources (with an appropriate scope) according to information stored securely in a server-side database.

On reflection, the example of `API SECRET` is misleading without additional context. I'll make a point to provide that in a quick update.
