### ISSUE TITLE
Xcode Build Configuration Files: Cannot read values other than strings using Configuration.value(for:)

### ISSUE THREAD

**Issue by schjonhaug** [NSHipster/articles#637]
Using the following code listed in the article,

```Swift
enum Configuration {
    static func value<T>(for key: String) -> T {
        guard let value = Bundle.main.infoDictionary?[key] as? T else {
            fatalError("Invalid or missing Info.plist key: \(key)")
        }

        return value
    }
}
```
, I'm unable to get values other than strings, because `Bundle.main.infoDictionary`'s values seem to be `NSTaggedPointerString` from what I can tell.

So if I define `MY_VALUE = 100.0` in the `.xcconfig` file, link it up in the target and try to get its value with `let myValue: Float = Configuration.value(for: "MY_VALUE")`, it will not work.

One could overload the function with each expected return type, but this does not seem to be as elegant as the proposed solution using generics.

```Swift
static func value(for key: String) -> Bool {
    guard let value = Bundle.main.infoDictionary?[key] as? String,
    let boolValue = Bool(value) else {
        fatalError("Invalid or missing Info.plist key: \(key)")
    }
    return boolValue
}
```

**Comment by mattt** [comment]
Thanks for writing in, @schjonhaug. Sorry to hear you were running into a problem here.

I just tried this again, and I'm pretty certain that `Bundle.main.infoDictionary` (and `Bundle.main.object(forInfoDictionaryKey:)`) return typed values according to the contents of the property list. That is, if you specify a Boolean, you get a Boolean back.

I think what you're actually running into is an unfortunate failure of `NSNumber` bridging. See [SE-0170](https://github.com/apple/swift-evolution/blob/master/proposals/0170-nsnumber_bridge.md) for a great discussion of this.

So converting to `Float` fails... what happens if you try `Double` instead?

```swift
let myValue: Double = Configuration.value(for: "MY_VALUE")
```

**Comment by schjonhaug** [comment]
Hi @mattt, thanks for getting back to me so quickly.

To expose values from `.xcconfig` in code, you'd have to specify the variables in `info.plist` as strings, right? Like so:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/84225/60905774-07126f00-a276-11e9-8bab-6461ddbc2f2e.png">

Please take a look at the attached project created by my colleague @IdaRiseng, showing a minimal setup of reading out variables from `.xcconfig`. You'll see that the string works fine, but that it'll crash on the other types. So, is the problem related to the fact that all variables in `Info.plist` are defined as strings?

[Test.zip](https://github.com/NSHipster/articles/files/3373927/Test.zip)

**Comment by mattt** [comment]
Ah, my mistake. I was coming at this with the wrong context. You're absolutely correct about needing to use strings for bridged `xcconfig` values. I'll update with a fix later today.

**Comment by mattt** [comment]
Thanks again for pointing this out, @schjonhaug. The article is now updated with the following code sample:

```swift
import Foundation

enum Configuration {
    enum Error: Swift.Error {
        case missingKey, invalidValue
    }

    static func value<T>(for key: String) throws -> T where T: LosslessStringConvertible {
        guard let object = Bundle.main.object(forInfoDictionaryKey:key) else {
            throw Error.missingKey
        }

        switch object {
        case let value as T:
            return value
        case let string as String:
            guard let value = T(string) else { fallthrough }
            return value
        default:
            throw Error.invalidValue
        }
    }
}

enum API {
    static var baseURL: URL {
        return URL(string: "https://" + try! Configuration.value(for: "API_BASE_URL"))!
    }

    static var key: String {
        return try! Configuration.value(for: "API_KEY")
    }
}
```
