### ISSUE TITLE
UIGraphicsImageRenderer available on iOS 10 or above | Image Resizing Techniques

### ISSUE THREAD

**Issue by AwaisFayyaz** [NSHipster/articles#638]
Hi Matt, 

Great Article. I was trying to resize and image using UIGraphicsImageRenderer but i am target iOS >= 9. i have this code 

 if #available(iOS 10.0, *) {
      let renderer = UIGraphicsImageRenderer(size: size)
      
      return renderer.image { (context) in
        image.draw(in: CGRect(origin: .zero, size: size))
      }
    } else {
      // Fallback on earlier versions
    }

How should i resize on earlier iOS versions? 

Thanks

**Comment by mattt** [comment]
In iOS 9 and earlier, use `UIGraphicsBeginImageContextWithOptions(_:_:_:)` / `UIGraphicsEndImageContext()`  and `UIGraphicsGetImageFromCurrentImageContext()`

```swift
UIGraphicsBeginImageContextWithOptions(size, false, 0.0)
defer { UIGraphicsEndImageContext }
let context = UIGraphicsGetCurrentContext()
image.draw(in: CGRect(origin: .zero, size: size))
let image = UIGraphicsGetImageFromCurrentImageContext()
```
