### ISSUE TITLE
Articles have swift now

### ISSUE THREAD

**Issue by sbingner** [NSHipster/articles#640]
Most of the articles seem to be providing swift code and the old Objective C code is missing.  It would be nice if Objective C code was still visible as well.

**Comment by mattt** [comment]
If Objective-C code samples are provided in an article, they'll be visible on the site. Were there any articles specifically that you're concerned about?

**Comment by sbingner** [comment]
I believe it may have been https://github.com/NSHipster/articles/blob/master/2014-08-24-wkwebview.md that I was looking at - it is from 2014 and I’m pretty sure I saw objc code there but now all I see is the Swift stuff
