### ISSUE TITLE
JavaScriptCore | Exchanging Promises between JavaScript and Swift

### ISSUE THREAD

**Issue by umangkathuria** [NSHipster/articles#642]
I am trying to use Swift to call a method in JavaScript which returns a promise.
Is there a way to handle that promise in native ?

or If i dont return a promise and use it as is, I get undefined. 
Something like this - 
function myFunction(){
     myPromise().then((result)=> {
      return(result);
      })
 }
If I call myFunction from Swift, I end up getting result. because it seems that it's returning even before the promise gets resolved.

Can you please help me out on this? 
Thanks in advance!

**Comment by mattt** [comment]
While I can't speak to this particular behavior, a quick search turned up [this article by Joseph Slinker](https://www.lucidchart.com/techblog/2018/02/14/javascriptcore-the-holy-grail-of-cross-platform/) describing their experience:

> The second thing you need to know is that the JavaScriptCore implementation of Promise is buggy. We never uncovered what the core issue is, other than that it can be unreliable. That’s why the above GitHub project contains an implementation of Promise provided by Bluebird. It was a drop-in replacement for us and immediately remedied all of the strange behaviors we were seeing when using the implementation of Promise that comes with JavaScriptCore.
