### ISSUE TITLE
BuildError by usage of try in article: https://nshipster.com/xcconfig/

### ISSUE THREAD

**Issue by matzino** [NSHipster/articles#647]
Hi @mattt ,

thank you for the good article about Xcode-Configuration-Files.

I followed your code and got a build error by the usage of try! The error message is: "try! cannot appear to the right of a non-assignment operator".

```
static var baseURL: URL {
        return URL(string: "https://" + try! Configuration.value(for: "API_BASE_URL"))!
}
```

As the message indicates the usage of "try?" doesn't help. I ended up with this code: 

```
    static var baseURL: URL? {
        do {
            let apiBaseUrlString: String = try Configuration.value(for: "API_BASE_URL")
            return URL(string: "https://" + apiBaseUrlString)
        } catch {
            print("baseURL creates an error: \(error)")
        }
        return nil
    }
```

Can you agree with that or did I missing something?

**Comment by mattt** [comment]
Thanks for calling this out, @matzino. I just updated the article with a working code sample, which  you can find here: https://nshipster.com/xcconfig/

```swift
enum API {
    static var baseURL: URL {
        return try! URL(string: "https://" + try! Configuration.value(for: "API_BASE_URL"))!
    }
}
```
