### ISSUE TITLE
Question about RelativeDateTimeFormatter

### ISSUE THREAD

**Issue by Ricardo1980** [NSHipster/articles#649]
Hello @mattt 

Here:
https://nshipster.com/formatter/#relativedatetimeformatter
You say RelativeDateTimeFormatter is only for iOS 13.

I remember in the past I used TTTTimeIntervalFormatter, but I see the project is archived because you say almost all features are now available using Apple APIs.

So, my question is, how can I get something like "5 min ago" or "1 hour ago" for iOS11 if I cannot use RelativeDateTimeFormatter neither TTTTimeIntervalFormatter

Thanks for suggestions, and thanks for that library.

**Comment by mattt** [comment]
FormatterKit is no longer being developed, but there's nothing stopping you from using it in your app until it supports iOS 13. If `TTTTimeIntervalFormatter` meets your needs, then go ahead and use it. Beyond that, I don't have any other recommendations for implementing this functionality yourself.
