### ISSUE TITLE
Bad info about Hashable in Identifiable article

### ISSUE THREAD

**Issue by Trzyipolkostkicukru** [NSHipster/articles#657]
```
But wait, would that contains call fail if trackedPackages were a Dictionary instead of an Array?
```
Have you meant `Set` instead of `Dictionary`? Dictionary cannot be a Collection of Packages, only a Collection of (Key, Value) pairs. If you meant `[Package:Value]`, then it doesn't make sense to say that packages are in the dictionary, and if you meant `[Key:Package]` then it doesn't make sense to talk about Package being Hashable, because dict values don't need to be Hashable.

```
If we instead provide our own implementation that only considers id, then trackedPackages.contains(_:) would return true,
```
When Hashable hashes collide, then they are compared using `==`, so it would correctly return false

**Comment by mattt** [comment]
@Trzyipolkostkicukru Yikes. Thanks for bringing this to my attention, @Trzyipolkostkicukru. This is clearly incorrect. Taking another look at this, I'm not entirely sure where I was going with this. I think maybe I was trying too hard to segue between Equatable and Hashable, and lost the plot along the way.

I took another pass at this with 875329eaac48af61e2f8367dfbda1b25189a6521. Please take a look and let me know if you see anything else that doesn't add up.

**Comment by Trzyipolkostkicukru** [comment]
Looks good to me! It's awesome how quickly you responded with the fix
