### ISSUE TITLE
Buggy order of precedence of config values?

### ISSUE THREAD

**Issue by dirtyhenry** [NSHipster/articles#658]
Hi! Thanks for the great [Xcode Build Configuration Files](https://nshipster.com/xcconfig/) article!

I tried to used xcconfig files to define my app name but couldn't do it as mentioned in the article. Which led me to doubt of the priority order mentioned in the article. 

So, how did you make it work?

--------- 

Here's what I done: 

### Prority 1. Xcode Project File Build Settings

<img width="830" alt="Screen Shot 2019-08-30 at 12 24 19" src="https://user-images.githubusercontent.com/456506/64013909-29f82b80-cb21-11e9-864b-170f8ea6e0ff.png">

### Priority 2. xcconfig File for the Xcode Project

I assigned a `Development.xcconfig` at the project level:

<img width="842" alt="Screen Shot 2019-08-30 at 12 25 27" src="https://user-images.githubusercontent.com/456506/64014004-5b70f700-cb21-11e9-80f7-26c77586bd1d.png">

In which I have: 

```
PRODUCT_NAME = "Yop Wop Hop"
```

### Priority 3. Active Target Build Settings

None is set. That's why it doesn't appear as bold. But it spoils that `Development.xcconfig` is being ignored.

<img width="856" alt="Screen Shot 2019-08-30 at 12 27 33" src="https://user-images.githubusercontent.com/456506/64014135-b7d41680-cb21-11e9-9e0b-65d7ad718dfd.png">

### Priority 4. xcconfig File for the Active Target

That's a CocoaPods defined file in which `PRODUCT_NAME` does not appear.

**Comment by dirtyhenry** [comment]
I realize my description is a little confusing. I'll rephrase to go straight to the point.

Instead of: 

1. Platform Defaults
1. Xcode Project File Build Settings
1. xcconfig File for the Xcode Project
1. Active Target Build Settings
1. xcconfig File for the Active Target

From [my tests](https://github.com/dirtyhenry/scaffold-ios/tree/settings), I believe the right order of precedence (from lowest to highest) is: 

1. Platform Defaults
1. xcconfig File for the Xcode Project
1. Xcode Project File Build Settings
1. xcconfig File for the Active Target
1. Active Target Build Settings

**Comment by mattt** [comment]
Thanks so much for bringing this to my attention, @dirtyhenry. (And further thanks for the update). You are indeed correct about the precedence of inherited build settings. I just pushed an update to the article today to reflect this.

https://nshipster.com/xcconfig/

**Comment by amirrezaeghtedari** [comment]
That's precedence problem is still available.
