### ISSUE TITLE
how to hide .xcconfig in ipa file?

### ISSUE THREAD

**Issue by techinpark** [NSHipster/articles#663]
How to hide `.xcconfig` files in ipa file? 
when unarchive `.ipa` file can found `.xcconfig` file 
please advice for me. 

Thanks.

**Comment by mattt** [comment]
`.xcconfig` files don't need to be a member of a target in order to be used by the build system. If they're appearing in the final `.ipa` file, you should remove them from the "Copy Bundle Resources" build phase (or the like) of your target.
