### ISSUE TITLE
Make sure that MetricKit InformationUnit parsing is correct.

### ISSUE THREAD

**Issue by nd-net** [NSHipster/articles#677]
In `2019-10-21-metrickit.md` you define a stored procedure, that uses multiples of 1024 for parsing bytes. I haven’t found in depth documentation of the JSON format, but behind the scenes the correlated properties use the data type `Measurement<UnitInformationStorage>`. 

`UnitInformationStorage` supports both [gigabytes and gibibytes](https://developer.apple.com/documentation/foundation/unitinformationstorage), so it would make sense that it serializes 10^9 Bytes = 1 GB (opposed to 2^30 Bytes _= 1 GB_, which could be serialized to 1 GiB)

**Comment by mattt** [comment]
That's a good catch, @nd-net. Thanks for writing in about that.

My original code was based on how Postgres represents file sizes (`pg_size_pretty()`), which [faced a similar problem with that Metric / IEC distinction](https://www.postgresql.org/message-id/20160730001838.GA22405%40momjian.us).

Checking the behavior in code, it appears that the `UnitInformationStorage` unit corresponding to `"GB"` indeed represents 10^9 bytes.

```swift
import Foundation

let measurement = Measurement<UnitInformationStorage>(value: 1, unit: .gigabytes)
let formatter = MeasurementFormatter()
formatter.string(from: measurement) // 1 GB
formatter.string(from: measurement.converted(to: .bytes)) // 1,000,000,000 byte
```

cd7c01a updates the implementation of `parse_byte_count` accordingly.
