### ISSUE TITLE
SwiftUI no suitable image found

### ISSUE THREAD

**Issue by avalanched** [NSHipster/articles#678]
I added SwiftUI previews (https://nshipster.com/swiftui-previews/)
When i try to run on an older simulator (pre-iOS13)

i get the following error message:

```
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/SwiftUI.framework/SwiftUI: mach-o, but not built for iOS simulator
```

**Comment by mattt** [comment]
If you set iOS 13 as the SDK target, you won't be able to run your app on a device or simulator running iOS <13. If you want to use Xcode Previews and debug a local build with a previous version of iOS, you'll need to run the app in a configuration that sets a compatible SDK target.

**Comment by avalanched** [comment]
Do you mean the `iOS Deployment target` because that is set at `iOS 10.0`
