### ISSUE TITLE
AVSpeech​Synthesizer article: the pronunciation tool no longer available on iOS

### ISSUE THREAD

**Issue by murphlab** [NSHipster/articles#685]
It appears the pronunciation tool has been removed from iOS. Any other ways to generate apple's non-standard IPA format?

UPDATE: Actually it's just moved. It's at:
Settings > Accessibility > VoiceOver > Speech > Pronunciations

**Comment by mattt** [comment]
Thanks for pointing this out, @murphlab. Fixed by cc8eecd.
