### ISSUE TITLE
2019-12-10-available.md appears to be missing a few words

### ISSUE THREAD

**Issue by Hanse00** [NSHipster/articles#696]
Around line 699, we have a paragraph that goes:
`However,
if your APIs wrap the underlying system call
in a way that doesn't expose the implementation details,
you may be able
For example,
an <abbr title="natural language processing">NLP</abbr>`.

It looks to me like there was meant to be something between “you may be” and “For example”.

**Comment by Hanse00** [comment]
@mattt since you wrote the article according to the blame, I imagine you’d be the best candidate for looking over the text, and seeing what might have gone wrong.

**Comment by mattt** [comment]
Thanks for pointing this out, @Hanse00. I just pushed a fix for this with bed35f3438a35e3d97e9e88be04c5b75c5e2dda7. Let me know if this still doesn't read correctly.

**Comment by Hanse00** [comment]
LGTM, thanks for the quick fix :)
