### ISSUE TITLE
Testing Swift API Availability

### ISSUE THREAD

**Issue by piers12** [NSHipster/articles#702]
I came across the awesome article on Swift API availability whilst looking at how I could potentially test some logic when using `if #available(iOS 13, *)` in a view model.

I can't seem to figure out a way to easily test this. I am looking to somehow inject it into my viewModel whilst passing in the default value of the `UIDevice.current.systemVersion`.

Was wandering if you have any idea's on this? Keep up the great articles!

**Comment by mattt** [comment]
Thanks for the kind words, @piers12!

`#available` is a compile-time determination, whereas `UIDevice.systemVersion` is a run-time determination; you can't mix the two together. If you want to test logic across different OS versions, the right way to do that would be to run the test target on those different OS versions.
