### ISSUE TITLE
Xcode Build Configuration Files: Which case will throw Error.invalidValue

### ISSUE THREAD

**Issue by akshitzaveri** [NSHipster/articles#712]
Hi! Thanks for the great [Xcode Build Configuration Files](https://nshipster.com/xcconfig/) article!
Using the following code in the article,

```swift
switch object {
    case (let value as T):
      return value
    case (let string as String):
      guard let value = T(string) else { fallthrough }
      return value
    default:
      throw Error.invalidValue
}
```

In which condition the default case of the above switch will execute?

**Comment by mattt** [comment]
Hi @akshitzaveri. An error will be thrown if `object` isn't of type `T`, or if it's a `String` but `T` can't be initialized with that strong, or if it's neither of type `T` or `String`.

I think what might be leading to confusion is my use of `fallthrough` in this code. Here's another, equivalent way you might write this code: 

```swift
switch object {
    case (let value as T):
      return value
    case (let string as String):
      guard let value = T(string) else { throw Error.invalidValue }
      return value
    default:
      throw Error.invalidValue
}
```

**Comment by akshitzaveri** [comment]
Hi @mattt , Thanks!

The confusion was not `fallthrough`.

So, as you said, if the `.xcconfig` file has a `String` value for `serverURL` key and I try to do this
```swift
let result: Bool? = try? Configuration.value(for: .serverURL)
```
then I will get `Error.invalidValue` as the code failed to convert the `String` to `Bool`.

I hope I understood it right. Thanks again.
