### ISSUE TITLE
Contact Tracing question

### ISSUE THREAD

**Issue by rob-dodson** [NSHipster/articles#718]
Why did Apple release a framework instead of an App? Are there going to be a lot third party apps doing contract tracing? Shouldn't there be just one per platform (iOS/Android)?

**Comment by mattt** [comment]
@rob-dodson That's a great question. I can think of a few reasons why they'd want to take this approach:

- Legally, each jurisdiction may have different regulations for how medical data is handled.
- Logistically, downloading the Positive Diagnosis Keys for every case in the world would be prohibitive and of limited usefulness. With existing shelter-in-place orders, everyone is effectively frozen in place; if I'm in the US, any new cases in Singapore don't affect me at all. The other way that one might accomplish geographic segmentation like this would require user location, which undermines the whole scheme.
- Optics-wise, it's a bad look for a giant multinational corporation to be coordinating a global health crisis. It's just not their role to play. Plus, I don't think either of them want to become a single point of failure for this.

I imagine that there will be a patchwork of systems adopting this. 

In the UK, the NHS (NHSX) is already building an app that, ostensibly, the national or local government could incorporate into their regulations. 

Here in the US, my guess is that you'll see states like California and New York being early adopters of apps developed either in-house or by a 3rd-party, and other states will follow their lead.

**Comment by rob-dodson** [comment]
That all makes sense. If all the apps in a region inter-operate that would work.
A related question: How will the action of declaring that you have the virus work? I mean if a person can just press a button in the app that could cause a lot of trouble if they don't actually have it. I would hope that could not be done on the phone but only on a back end system by your doctor. Anyway, this is all fascinating. Brave new world. Thanks for the write up.

**Comment by mattt** [comment]
> How will the action of declaring that you have the virus work? I mean if a person can just press a button in the app that could cause a lot of trouble if they don't actually have it. I would hope that could not be done on the phone but only on a back end system by your doctor. 

That's definitely a concern. One would hope that any system that implements this will enforce rigorous infosec standards, to secure their data as well as their personnel. Like everything else, technology will only get us so far; at some point, there has to be a person on the other end.
