### ISSUE TITLE
Escape double backslash in xcconfig

### ISSUE THREAD

**Issue by a2** [NSHipster/articles#730]
In the [Xcode Build Configuration Files](https://nshipster.com/xcconfig/) article, there is a note about trying to include a URL in an xcconfig file, since Xcode treats `//` as a comment delimiter. I remember hearing or reading somewhere that you can separate the double slashes with an empty interpolation `$()` so that you then have the following:

```
API_BASE_URL = "https:/$()/api.example.com"
```

Wanted to create an issue to start a dialogue on this before I made a PR to remove the warning.

**Comment by mattt** [comment]
Hi @a2. Thanks for writing in! This has been discussed on a few past occasions (#615, #706). Reflecting on this again now, my opinion hasn't really changed from my original take:

> I'm aware of this workaround, but don't particularly want to encourage its use by mentioning it in the article. And given that non-HTTPS URLs require an explicit exemption entitlement in iOS apps, I don't see an urgent need to support variable schemes in a way that requires this approach.

That said, I remain open to any arguments about why this is useful (particularly outside of the http / https context)

**Comment by a2** [comment]
That’s a fair assessment. Thanks for the explanation. :+1:
