### ISSUE TITLE
script not working 2019-09-02-dark-mode.md

### ISSUE THREAD

**Issue by forsan** [NSHipster/articles#743]
Thank you for the amazing article.

I'm just trying to run the below script but always get this error

`
scriptall.rb:7: syntax error, unexpected end, expecting when
    end
scriptall.rb:76: syntax error, unexpected end-of-input, expecting end`

```ruby
require 'nokogiri'

def name_for_rgba_components(red, green, blue, alpha)
    case format('#%02X%02X%02X%02X', red, green, blue, alpha)
    # Return named color matching RGBA components
    # e.g. "#F8CB00FF" => "Accent"
    end
end

def name_for_white_and_alpha_components(white, alpha)
    # Return named color matching white and alpha components
    # e.g. 0.9 => "Off-White"
end

....
```

thank you

**Comment by mattt** [comment]
Like the error message says, you're missing a `when` in your [`case` statement](https://www.rubyguides.com/2015/10/ruby-case/). Beyond that, I can't really help you; the script is provided "as-is" as a bonus and isn't the focus of the article.
