### ISSUE TITLE
https://nshipster.com/xcconfig, using config=Debug doesn't work

### ISSUE THREAD

**Issue by garvankeeley** [NSHipster/articles#745]
Using `config=Debug` doesn't work that I can see:
`ONLY_ACTIVE_ARCH[config=Debug] = YES` or the equivalent (IIUC) `ONLY_ACTIVE_ARCH[config=Debug][sdk=*][arch=*] = YES`
Produces no results in Xcode UI when that setting is viewed.

This doc [here](https://pewpewthespells.com/blog/xcconfig_guide.html#CondVarConfig) warns about problems using config=Debug (albeit different still than what I am seeing), which suggests it creates subsettings that may not be matched (and says one should not rely on this to work):

>  using [config=] should almost never be the desired behavior when assigning values based on build configuration name.

LMK if you need more of an STR with a demo project.

**Comment by garvankeeley** [comment]
Closing, the problems is `config` isn't resolving to debug/release due to changes elsewhere

**Comment by benrudhart** [comment]
@garvankeeley did you find a proper solution to this issue? I think I'm running into the same one but we're not overriding the value somewhere else
