### ISSUE TITLE
Xcode Build Configuration Files: Is it possible to use boolean value in xcconfig

### ISSUE THREAD

**Issue by zhouhao27** [NSHipster/articles#766]
I'm wondering if it's possible to use boolean value in xconfig file? Thanks.

**Comment by mattt** [comment]
Entries in Xcode build configuration files key/value pairs of strings. If you want to interpret a String as a Boolean, you'd need some code like what's described in the section ["Accessing Build Settings from Swift"](https://nshipster.com/xcconfig/#accessing-build-settings-from-swift). Unfortunately, there are many possible mappings between `String` and `Boolean`, so your implementation would need to cover whatever you use in your configuration file (for example: `"1"`, `"true"`, and `"YES"`.
