### ISSUE TITLE
Wrong day in the example of the DateComponents

### ISSUE THREAD

**Issue by ostaptyv** [NSHipster/articles#767]
In the https://nshipster.com/datecomponents/#date-components-as-a-representation-of-a-calendar-date section in the all date components properties example, you have two wrong fields in the "Component-Value" table: day and nanoseconds. In the table:

```
day - 3
nanosecond - 123456789,
```

while in fact, it is:

```
day - 10
nanosecond - 0
```

<img width="1440" alt="Screenshot 2021-04-27 at 21 18 39" src="https://user-images.githubusercontent.com/45757727/116292317-38876200-a79e-11eb-9945-fb4890d7a9ec.png">

Please recheck the example because I got confused and stuck for a couple of minutes trying to understand where the actual day is stored 😅

**Comment by mattt** [comment]
Thanks for catching this, and apologies for any confusion there. Fixed by 187c7f7.
