### ISSUE TITLE
"Could not load Network Link Conditioner Preferences Pane" does not point to any logs?

### ISSUE THREAD

**Issue by deanhiller** [NSHipster/articles#772]
I have xcode 13 on MAC Big Sur 11.6 and after install, all I get is the above error message.  I have no idea where any logs are or what is wrong and why I can't use network link conditioner.  It looks like a great tool, but I can't seem to use it.  (referred here from https://nshipster.com/network-link-conditioner/ )

Error messages pointing to log locations would be amazing in applications to at least give developers a place to look so we can feed logs back into a ticket.

**Comment by oscarvalente** [comment]
@deanhiller apparently the Network Link Conditioner that comes with [Additional Tools for XCode 12.5 ](https://download.developer.apple.com/Developer_Tools/Additional_Tools_for_Xcode_12.5/Additional_Tools_for_Xcode_12.5.dmg) works fine (XCode 13.1, BigSur 11.6).
